LAT, fix: Fix compilation error caused by duplicate macro definition
This fixes the following compilation failure on AOSC OS:

../linux-user/syscall_defs.h:1533:9: 错误：“MAP_HUGE_2MB”重定义 [-Werror]
 1533 | #define MAP_HUGE_2MB     (21 << HUGETLB_FLAG_ENCODE_SHIFT)
      |         ^~~~~~~~~~~~
In file included from /usr/include/bits/mman.h:32,
                 from /usr/include/sys/mman.h:41,
                 from /home/lauren/lat/include/sysemu/os-posix.h:29,
                 from /home/lauren/lat/include/qemu/osdep.h:161,
                 from ../linux-user/i386/signal.c:19:
/usr/include/bits/mman-linux.h:70:9: 附注：这是先前定义的位置
   70 | #define MAP_HUGE_2MB    (21 << MAP_HUGE_SHIFT)
      |         ^~~~~~~~~~~~
../linux-user/syscall_defs.h:1534:9: 错误：“MAP_HUGE_1GB”重定义 [-Werror]
 1534 | #define MAP_HUGE_1GB     (30 << HUGETLB_FLAG_ENCODE_SHIFT)
      |         ^~~~~~~~~~~~
/usr/include/bits/mman-linux.h:76:9: 附注：这是先前定义的位置
   76 | #define MAP_HUGE_1GB    (30 << MAP_HUGE_SHIFT)

Signed-off-by: Hanlu Li <heuleehanlu@gmail.com>