LATX, fix: Remove unused variable in aot_do_tb_reloc
Fixes compilation error with -Werror=unused-variable flag enabled.

The variable 'base' defined at target/i386/latx/sbt/aot.c:1228 is
assigned but never used, causing the following compilation error:
  ../target/i386/latx/sbt/aot.c:1228:18: error: unused variable 'base'

Remove the unused variable to resolve the build failure.

Signed-off-by: Hanlu Li <heuleehanlu@gmail.com>